@server = https://texai-crispy-enigma-j4q5xwg7735p95-8080.preview.app.github.dev
@instrumentos = {{server}}/api/instrumentos
###
GET {{instrumentos}}
###
POST {{instrumentos}}
Content-Type: application/json

{
    "nombre": "Quena",
    "categoria": "Viento",
    "descripcion": "burglar"
}